config: "facebook/bart-base"               # Pre-trained model or configuration to use
save_path: "saved_models/bart_sum_rate"    # Directory to save the model checkpoints
log_dir: "runs/bart_sum_rate_logs"         # Directory to store logs for TensorBoard

num_epochs: 30                             # Total number of epochs for training
mid_epoch: 10                              # Epoch after which to switch from summarization to classification

# Path to load summarization weights. Set load_checkpoint to False if training from scratch.
load_checkpoint: False
summarization_weights_path: saved_models/bart_sum_rate/best_loss_model_classification    

summarization:
  batch_size: 8                           # Batch size for summarization training and evaluation
  lr: 0.00001                             # Learning rate for summarization task optimizer
  weight_decay: 0.1                       # Weight decay for the summarization optimizer

classification:
  batch_size: 32                          # Batch size for classification training and evaluation
  lr: 0.00001                             # Learning rate for classification task optimizer
  weight_decay: 0.02                      # Weight decay for the classification optimizer
